version: '3.7'
services:
  integration:
    container_name: int
    environment:
      - TZ=America/Sao_Paulo
    build: .
    entrypoint: ./start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 5532:3000
    depends_on:
      - int_prod

  int_prod:
    container_name: integration_prod
    image: mongo
    restart: on-failure
    volumes:
      - ./.docker/dbdata:/data/integration_prod
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=app
    
  mongo-express:
    container_name: mongo_express_5
    image: mongo-express
    restart: always
    ports:
      - 5533:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=int_prod
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - int_prod
